version: "3.5"

services:
  redis:
    image: redis
    restart: unless-stopped
    hostname: redis
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    depends_on:
      - redis
    restart: unless-stopped
    hostname: logstash
    volumes:
      - ./config/logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    env_file:
      - .env
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    depends_on:
      - logstash
    restart: unless-stopped
    hostname: elasticsearch
    environment:
      - "xpack.security.enabled=false"
      - "discovery.seed_hosts=127.0.0.1:9300"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}"
    volumes:
      - /usr/share/elasticsearch/data
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    depends_on:
      - elasticsearch
    restart: unless-stopped
    hostname: kibana
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    env_file:
      - .env
    ports:
      - "5601:5601"
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}

  node:
    build: .
    depends_on:
      - redis
    restart: unless-stopped
    hostname: node
    volumes:
      - .:/app
      - ./app/node_modules
    working_dir: /app
    command: node ./index.js
    env_file:
      - .env
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE}
        max-file: ${DOCKER_LOG_MAX_FILE}